// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCqvOJv2CYIQnRTnKDY776Xk4QOgnViuY',
    appId: '1:691288987638:web:84812f98d31484a2db99d7',
    messagingSenderId: '691288987638',
    projectId: 'rental-car-app-1c9a4',
    authDomain: 'rental-car-app-1c9a4.firebaseapp.com',
    storageBucket: 'rental-car-app-1c9a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwFbBK8xDGtHZ71H-RPr0NEGgFdvZPFY0',
    appId: '1:691288987638:android:45824095ed8d799bdb99d7',
    messagingSenderId: '691288987638',
    projectId: 'rental-car-app-1c9a4',
    storageBucket: 'rental-car-app-1c9a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHHm3117CECbBqtdeNE-5tkqlNAThImAc',
    appId: '1:691288987638:ios:228138e38378b9a7db99d7',
    messagingSenderId: '691288987638',
    projectId: 'rental-car-app-1c9a4',
    storageBucket: 'rental-car-app-1c9a4.firebasestorage.app',
    iosBundleId: 'com.example.rentalCarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHHm3117CECbBqtdeNE-5tkqlNAThImAc',
    appId: '1:691288987638:ios:228138e38378b9a7db99d7',
    messagingSenderId: '691288987638',
    projectId: 'rental-car-app-1c9a4',
    storageBucket: 'rental-car-app-1c9a4.firebasestorage.app',
    iosBundleId: 'com.example.rentalCarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCqvOJv2CYIQnRTnKDY776Xk4QOgnViuY',
    appId: '1:691288987638:web:1321ae0e1125bccbdb99d7',
    messagingSenderId: '691288987638',
    projectId: 'rental-car-app-1c9a4',
    authDomain: 'rental-car-app-1c9a4.firebaseapp.com',
    storageBucket: 'rental-car-app-1c9a4.firebasestorage.app',
  );
}
